### ISSUE TITLE
BTTV channel emotes not working in videos

### ISSUE THREAD

**Issue by hakasedev** [Lordmau5/The-FFZ-Addon-Pack#10]
I'm watching this video:

https://www.twitch.tv/videos/163684317

Global BTTV emotes such as LUL are working, but channel BTTV emotes such as FeelsPepoSpin are not.

**Comment by Lordmau5** [comment]
Seems to work fine on my end - didn't see someone post a single FeelsPepoSpin yet...
![image](https://user-images.githubusercontent.com/1345036/28947644-41ffa92a-78b1-11e7-8d67-9775ef465bf8.png)

**Comment by hakasedev** [comment]
Interesting. It would seem that now every bttv channel emote is working on my end too.
