### ISSUE TITLE
Update to support FFZ 4.0.

### ISSUE THREAD

**Issue by winneon** [Lordmau5/The-FFZ-Addon-Pack#12]
I understand FFZ 4.0 is currently in beta and does not have the full functionality of prior FFZ versions. Once emoji support is properly implemented into FFZ 4.0, I hope this addon pack is updated to support it. It's the only way I'm able to keep FFZ as my only Twitch extension instead of relying on BTTV for their emotes.

**Comment by Lordmau5** [comment]
Sorry for the late response, I've been on vacation last week.

I've looked into FFZ v4 support but I won't be able to immediately support *everything* from the start.

Right now, global and channel emotes are working, as well as GIF emotes (the option to change how GIF emotes are shown is also in already).

I'll probably push that build later tonight after I checked if there's more I can already implement.

**Comment by Lordmau5** [comment]
Basic support for FFZ v4 is now in.
Only global and channel emotes of BTTV are currently working.

More features will be implemented once resources / methods for those are available.

The source code will be pushed once I had time to re-visit a few other things.

**Comment by winneon** [comment]
Thank you!

**Comment by Lordmau5** [comment]
No problem :)

In case there's any more questions or you need quick assistance, don't hesitate to join the Discord and ask away.
Or just open another issue, I'm not your dad lol
