### ISSUE TITLE
D: emote doesn't work

### ISSUE THREAD

**Issue by bakugo** [Lordmau5/The-FFZ-Addon-Pack#15]
What the title says. The BTTV Global `D:` emote doesn't show up. All others seem to work, including `:tf:`

**Comment by Lordmau5** [comment]
Make sure you have this setting enabled, as by default the override emotes (like `D:`) are disabled
![image](https://user-images.githubusercontent.com/1345036/48594888-daaa8b00-e952-11e8-88fb-66dd411fcb70.png)

**Comment by bakugo** [comment]
You're right, I didn't have it enabled. Sorry about that!

**Comment by bakugo** [comment]
That said, I'm left wondering: what does "override" refer to? There are no other emotes like that (that I know of)

**Comment by Lordmau5** [comment]
There was one "override" emote that had non-alphanumeric characters in it - I think it was `:mooning:`, so yeah.

It would affect every emote containing non-alphanumeric characters, such as the colon or an exclamation mark
