### ISSUE TITLE
Overlapping emotes not overlapping

### ISSUE THREAD

**Issue by 2tbwXj46BDbdNBRV79DS** [Lordmau5/The-FFZ-Addon-Pack#16]
SoSnowy IceCold SantaHat are not overlapping for me as they would if i was using bttv only

**Comment by Lordmau5** [comment]
This was fixed in the newest update.
Sadly, nobody of the BTTV team gave me a heads-up that they were live, and their "offset" is still hardcoded and not in their API, so effectively I always need to get rid of the code and put it back in later.

**Comment by RedSnt** [comment]
It's happening again with 'cvHazmat'.
