### ISSUE TITLE
Firefox - 1920x1080 Animated BTTV Emotes not looping correctly

### ISSUE THREAD

**Issue by Swiftpaws** [Lordmau5/The-FFZ-Addon-Pack#22]
In FF (Tested 69 and 70) emotes on my second monitor 1920x1080  (main one is 2160x1440) do not loop correctly.
From what I observed every time a new message with an animated emote comes in all current animations are restarted.

Some even weirder behavior is that some emotes (forsenWC) seem to stack on top of each other) - you can actually see the finished animation while a new one slides over it.

### AddonList
Decentraleyes - Could this extension be fucking with the loops ?
ffCK Overlays
FrankerFaceZ
Ghostery
HTTPS Everywhere
I don't care about cookies
uBlock Origin

**Comment by Lordmau5** [comment]
That is default Firefox behavior.
It restarts all GIFs so they're in sync and the browser has to render them only once for performance reasons.

Nothing I can do about it - I'm also unsure whether or not there is a setting in Firefox to change that 🤔

**Comment by Swiftpaws** [comment]
I have found the issue.
So I have 3 monitors 4k, 2k and 1080p ...

It only fails to behave correctly on my 1080p one ... Because of windows ui scaling !!
My other two monitors use 125% and 175% - The 1080p one uses 100%.

So I switched to 125% on the 1080p one and .. it worked. 
- Switching any of my other two to 100% also gives me the same issue.
**The only question now is why it wont run properly on 100%**

**Comment by Swiftpaws** [comment]
Nevermind windows is not the culprit here. Its scaling in general.

If you use ctrl & mousewheel in firefox it also bugs out...

**Comment by Swiftpaws** [comment]
Demonstration: (I used CTRL&Mousewheel to zoom in through FF)
https://i.imgur.com/94czoo7.gif

**Comment by Lordmau5** [comment]
Doesn't change the fact that it's a Firefox issue and I can't fix anything about it.

**Comment by broken-49** [comment]
> 
> 
> That is default Firefox behavior.
> It restarts all GIFs so they're in sync and the browser has to render them only once for performance reasons.
> 
> Nothing I can do about it - I'm also unsure whether or not there is a setting in Firefox to change that 🤔

If you use an actual BTTV browser extension instead of FFZ addon, animation in GIF emotes does not restart and it loops properly when new messages appear with same emotes. How come this Firefox behavior does not affect BTTV extension?

**Comment by Lordmau5** [comment]
Looking through their code I can't spot anything obvious that FFZ would be doing different.
They're both simply using an `<img>` element and.. nothing special besides that.

**Comment by Swiftpaws** [comment]
@Lordmau5 I think omitting srcset 1x could be the reason why it is looping correctly with the bttv addon.

![image](https://user-images.githubusercontent.com/18440081/91435174-3ca55d80-e866-11ea-9d3c-7fa351387d82.png)
