### ISSUE TITLE
Animated GIF Emotes causes video stuttering

### ISSUE THREAD

**Issue by juanjotoronja** [Lordmau5/The-FFZ-Addon-Pack#25]
Toggling video popout starts to stutter every second while audio plays normally, I noticed this behavior while the browser was minimized and tab changing. This bug was reported in this [thread](https://forums.opera.com/topic/34584/video-pop-out-hiccups-stutters-when-originating-tab-is-in-background-fix), already tried changing "d3d11-video-decoder" and "use-angle" flags also disabling "Use hardware acceleration when available" with no success. After I disabled the "The-FFZ-Addon-Pack" video popout stopped stuttering, enabled it back and the stutters returned so after some tests I found the culprit.

GIF Emotes : Static (plays normally without stutter)
                     Animated (makes video popout stutter every second)

Browser: Opera GX / LVL1 (core: 64.0.3417.150)
OS: Windows 7 64-bit

**Comment by Lordmau5** [comment]
You're the first to report this issue so I'm thinking it is some performance-related setting / design-choice within Opera GX itself that is causing these issues.
Nothing I can do about it, sadly...
