### ISSUE TITLE
Firefox Animated Emotes Restart on New Message 

### ISSUE THREAD

**Issue by Houdini111** [Lordmau5/The-FFZ-Addon-Pack#29]
I've been using Firefox for years so I wasn't aware that there's a difference in behavior but once I heard about it I checked for myself and sure enough, there's a difference in behavior between Chromium (Edge 93.0.1.961.52 specifically tested) and Firefox (92.0). 

I detailed the findings in this [Imgur album](https://imgur.com/a/8YOyFpK) (which also includes a longer video to examine as you please). 
On Chromium animate emotes do not restart to the first frame when a new emote is posted, newly posted emotes start where previous emotes already were. 
On Firefox the emotes will restart to their first frame upon receiving a new message. 

Here it is demonstrated in a cropped and synchronized pair of messages. 
Before:
![Frame1](https://user-images.githubusercontent.com/23154194/134597952-89496de3-fe48-4e24-aa4e-712245edd21a.png)
After: 
![Frame2](https://user-images.githubusercontent.com/23154194/134597966-bc505538-f329-4b5e-88a3-1ccd20c69c24.png)

As far as I'm aware this behavior is the same on any channel with any emote but in case it matters, the emote found here is "WanWan" by "Salzor_"  and the channel is "Cirno_TV".

**Comment by Lordmau5** [comment]
This is an issue with Firefox that, to this day, still hasn't been fixed.

The only solution to this is to either wait for Firefox to bring out a fix or switch to another browser.

https://github.com/FrankerFaceZ/FrankerFaceZ/issues/985
