### ISSUE TITLE
[Feature request] Add button to only enable highlight sound when moderating

### ISSUE THREAD

**Issue by Ethan-BB** [Lordmau5/The-FFZ-Addon-Pack#32]
If possible, please consider adding a toggle into "FFZ:AP Core" section to only enable highlight sound when moderating, pretty much with the same logic as the one that already exists in "First Message Highlight".
Thank you

**Comment by Lordmau5** [comment]
You can achieve that with a custom profile in FFZ
![image](https://github.com/Lordmau5/The-FFZ-Addon-Pack/assets/1345036/0d380fb7-4c5c-45e4-a558-1d9c3ae54ba2)

Open the control center, click the dropdown where it says "Default Profile", select "Moderation" and do your changes that you only want to have when you have moderator privileges there :)
