### ISSUE TITLE
FFZ-AP 2.2.0 breaking firefox multi-processing.

### ISSUE THREAD

**Issue by krab** [Lordmau5/The-FFZ-Addon-Pack#6]
FFZ itself don't. in `about:support` multi windows `1/1 enabled`.
However after installing FFZ-AP `0/1 disabled by addons`.

**Comment by Technoblazed** [comment]
Nice report, that makes 👌  sense

**Comment by Lordmau5** [comment]
Can you confirm it's fixed with the newest Firefox build, 2.2.2?

You can get it from the [FFZ:AP Website](https://ffzap.lordmau5.com/).

**Comment by krab** [comment]
Yes fixed in 2.2.2.
