### ISSUE TITLE
BTTV Emotes

### ISSUE THREAD

**Issue by Afireee** [Lordmau5/The-FFZ-Addon-Pack#8]
i have FFZ:AP and I enabled all BTTV emotes in the settings, but today (May 12 2017) all BTTV emotes are not showing in the chat... What Happened?

**Comment by Lordmau5** [comment]
If that occurs, it's a 99% chance that stuff on BTTV's end is fucking up and thus the emotes can't be loaded.

This means that in both, FFZ:AP **and** BTTV itself, BTTV emotes aren't working.

Nothing I can do about that. Emotes seem to work fine again though.
