### ISSUE TITLE
Enable emotes for clips

### ISSUE THREAD

**Issue by dsfgtrdc** [Lordmau5/The-FFZ-Addon-Pack#9]
Emotes are not working with clips at the moment.
Example clip: https://clips.twitch.tv/WrongCourteousFloofDatSheffy

**Comment by Lordmau5** [comment]
Neither are FFZ emotes, which means FFZ isn't loaded on that page.

That's something SirStendec needs to fix in [FrankerFaceZ](https://github.com/FrankerFaceZ/FrankerFaceZ), sadly.
